'use strict';
const express=require('express'),crypto=require('node:crypto'),db=require('../../database');
const {requireAuth,requireViewCases,requireEditCases}=require('../../middleware/authentication');
const A=require('./addressbook'),router=express.Router();
router.use(requireAuth,requireViewCases);
const contactEvents=require('../office/events').middleware('officeContacts');
router.use((req,res,next)=>['/views','/communications/sync'].includes(req.path)?next():contactEvents(req,res,next));
const handle=fn=>async(req,res)=>{try{res.json(await fn(req))}catch(e){res.status(e.status||500).json({error:e.status?e.message:'Adressbuch konnte nicht gespeichert werden.',...(e.code?{code:e.code,candidates:e.candidates}:{} )})}};
const trash=require('./addressbook-trash');
router.get('/trash',handle(r=>trash.list(r.session)));
router.post('/trash',requireEditCases,handle(r=>trash.remove(r.body,r.session)));
router.post('/trash/restore',requireEditCases,handle(r=>trash.restore(r.body,r.session)));
router.post('/duplicates',handle(r=>require('./addressbook-duplicates').find(r.body,r.session)));
const sync=require('./addressbook-sync');
router.get('/sync',handle(r=>sync.state(r.query,r.session)));
router.post('/sync/remote',requireEditCases,handle(r=>sync.remoteOptions(r.body,r.session)));
router.post('/sync/link',requireEditCases,handle(r=>sync.link(r.body,r.session)));
router.patch('/sync',requireEditCases,handle(r=>sync.toggle(r.body,r.session)));
router.delete('/sync',requireEditCases,handle(r=>sync.unlink(r.body,r.session)));
router.post('/sync/run',requireEditCases,handle(r=>sync.run(r.body,r.session)));
router.get('/contact',handle(r=>A.details(r.query.scope,r.query.caseId||'',r.query.id,r.session)));
router.get('/history',handle(r=>A.historyPage(r.query.scope,r.query.caseId||'',r.query.id,r.session,r.query.cursor)));
router.get('/communications',handle(r=>A.communicationPage(r.query.scope,r.query.caseId||'',r.query.id,r.session,r.query.cursor)));
const views=require('./addressbook-views');
router.get('/views',handle(r=>views.list(r.session)));
router.put('/views',handle(r=>views.save(r.body,r.session)));
router.delete('/views',handle(r=>views.remove(r.body,r.session)));
router.post('/import-vcards',requireEditCases,handle(r=>require('./addressbook-vcard-import').importContacts(r.body,r.session)));
router.post('/communications/sync',handle(r=>require('./addressbook-communications').sync(r.body,r.session)));
router.patch('/person',requireEditCases,handle(r=>A.savePerson(r.body,r.session)));
const merge=require('./addressbook-merge');
router.get('/merges',handle(r=>merge.result(r.query.caseId,r.session)));
router.post('/merge',requireEditCases,handle(r=>merge.merge(r.body,r.session)));
router.post('/unmerge',requireEditCases,handle(r=>merge.unmerge(r.body,r.session)));
router.patch('/contact',requireEditCases,handle(r=>{
 const {scope,caseId='',id,patch,version}=r.body;A.authorize(r.session,scope,caseId,true);const changes=A.validatePatch(patch);
 const row=A.get(scope,caseId,id);if(!row)A.fail(404,'Kontakt nicht gefunden.');const next={...A.data(row),...changes};
 if(!String(next.institution||'').trim()&&!String(next.lastName||'').trim())A.fail(400,'Bitte Institution oder Nachname angeben.');
 if(!version)A.fail(400,'Die Kontaktversion fehlt. Bitte neu laden.');A.replace(scope,caseId,id,changes,r.session,version);return A.details(scope,caseId,id,r.session);
}));
router.post('/contact',requireEditCases,handle(r=>{
 const {scope,caseId='',patch,creationId}=r.body;A.authorize(r.session,scope,caseId,true);
 if(creationId!==undefined&&(typeof creationId!=='string'||!/^[a-z0-9-]{36}$/i.test(creationId)))A.fail(400,'Ungültige Kennung für die Kontaktanlage.');
 if(creationId&&A.get(scope,caseId,creationId))return A.details(scope,caseId,creationId,r.session);
 if(creationId&&db.prepare("SELECT 1 FROM addressbook_trash t,json_each(t.data_json,'$.rows') r WHERE json_extract(r.value,'$.id')=? AND json_extract(r.value,'$.scope')=? AND t.restored_at IS NULL").get(creationId,scope))A.fail(409,'Der angelegte Kontakt wurde inzwischen in den Papierkorb verschoben.');
 const next=A.validatePatch(patch);
 if(!String(next.institution||'').trim()&&!String(next.lastName||'').trim())A.fail(400,'Bitte Institution oder Nachname angeben.');
 const candidates=require('./addressbook-duplicates').find({scope,caseId,patch:next},r.session).candidates;
 if(candidates.length&&r.body.allowDuplicates!==true){const error=new Error('Ähnliche Kontakte vorhanden. Bitte die Vorschläge prüfen.');error.status=409;error.code='duplicates';error.candidates=candidates;throw error;}
 if(next.people)next.people=next.people.map(p=>require('../../../frontend/addressbook-contact-tools').withWays(p));
 if(next.contactWays)Object.assign(next,require('../../../frontend/addressbook-contact-tools').withWays(next));
 const id=creationId||crypto.randomUUID();next.status=next.status||'Aktiv';next._category=next._category||'soziales';next.createdAt=new Date().toISOString();
 if(scope==='case'){if(!db.prepare('SELECT id FROM cases WHERE id=?').get(caseId))A.fail(404,'Fall nicht gefunden.');db.prepare('INSERT INTO case_contacts(id,case_id,data_json,updated_by) VALUES(?,?,?,?)').run(id,caseId,JSON.stringify(next),r.session.userId)}
 else db.prepare('INSERT INTO office_contacts(id,data_json,updated_by) VALUES(?,?,?)').run(id,JSON.stringify(next),r.session.userId);
 A.record(scope,caseId,id,null,next,r.session);A.notify(scope,caseId,id,next);return A.details(scope,caseId,id,r.session);
}));
router.post('/assign',requireEditCases,handle(r=>A.assign(r.body,r.session)));
router.post('/followup',requireEditCases,handle(r=>require('./addressbook-followup').save(r.body,r.session)));
router.post('/standard',requireEditCases,handle(r=>A.standard(r.body,r.session)));
router.post('/restore',requireEditCases,handle(r=>{
 const {scope,caseId='',id,historyId,version}=r.body;A.authorize(r.session,scope,caseId,true);
 const h=db.prepare('SELECT * FROM addressbook_history WHERE id=? AND scope=? AND contact_id=? AND case_id=?').get(historyId,scope,id,caseId);if(!h)A.fail(404,'Änderung nicht gefunden.');
 const patch={};for(const [k,v] of Object.entries(JSON.parse(h.changes_json)))if(A.FIELDS.includes(k))patch[k]=v.before??(['people','addresses','contactWays'].includes(k)?[]:'');
 if(!Object.keys(patch).length)A.fail(400,'Fallzuordnungen und Standardempfänger bitte unter „Fälle & Standard“ ändern.');
 const row=A.get(scope,caseId,id);if(!row)A.fail(404,'Kontakt nicht gefunden.');if(patch.addresses&&!patch.addresses.some(a=>a.id===(patch.preferredAddressId??A.data(row).preferredAddressId)))patch.preferredAddressId='';const next={...A.data(row),...patch};if(!next.institution&&!next.lastName)A.fail(400,'Die Anlage eines Kontakts lässt sich hier nicht rückgängig machen.');
 if(!version)A.fail(400,'Kontaktversion fehlt.');A.replace(scope,caseId,id,patch,r.session,version);return A.details(scope,caseId,id,r.session);
}));
router.post('/detach',requireEditCases,handle(r=>{
 const {scope,caseId='',id,targetCaseId,contactId}=r.body;A.authorize(r.session,scope,caseId);A.authorize(r.session,'case',targetCaseId,true);
 const cid=A.centralId(scope,id),row=A.get('case',targetCaseId,contactId);if(!cid||!row||A.centralId('case',contactId)!==cid)A.fail(404,'Zuordnung nicht gefunden.');
 db.transaction(()=>{db.prepare('DELETE FROM addressbook_links WHERE case_contact_id=?').run(contactId);const next=A.data(row);delete next.centralContactId;db.prepare('UPDATE case_contacts SET data_json=? WHERE id=?').run(JSON.stringify(next),contactId);A.record('case',targetCaseId,contactId,A.data(row),next,r.session)})();
 A.notify('case',targetCaseId,contactId,A.data(A.get('case',targetCaseId,contactId)));
 return A.details(scope,caseId,id,r.session);
}));
module.exports=router;
