'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ab-organizer-'));process.env.RUNTIME_ROOT=dir;process.env.DB_PATH=path.join(dir,'test.db');process.env.ENCRYPTION_KEY='54'.repeat(32);process.env.DOCUMENTS_DATA_ROOT=path.join(dir,'data');
const db=require('../src/database'),A=require('../src/modules/contacts/addressbook'),O=require('../src/modules/contacts/addressbook-organizer'),D=require('../frontend/addressbook-extras-data'),T=require('../frontend/addressbook-contact-tools'),V=require('../frontend/addressbook-vcard'),Trash=require('../src/modules/contacts/addressbook-trash'),S=require('../src/modules/contacts/addressbook-sync'),P=require('../src/modules/contacts/addressbook-sync-provider');
const admin={userId:1,isAdmin:true},reader={userId:2,canViewCases:true,canEditCases:false},editor={userId:3,canViewCases:true,canEditCases:true};
db.prepare("INSERT INTO users(id,username,password_hash,is_admin,allow_online) VALUES(1,'admin','x',1,1),(2,'reader','x',0,1),(3,'editor','x',0,1)").run();db.prepare("INSERT INTO cases(id,label,owner_user_id) VALUES('a','Fall A',1),('b','Fall B',2),('c','Fall C',3)").run();
const create=(id,data={},scope='office',caseId='')=>db.prepare('INSERT INTO '+(scope==='office'?'office_contacts':'case_contacts')+'(id,'+(scope==='case'?'case_id,':'')+'data_json) VALUES(?,'+(scope==='case'?'?,':'')+'?)').run(id,...(scope==='case'?[caseId]:[]),JSON.stringify({institution:id,...data}));
const patch=(id,p,scope='office',caseId='')=>A.replace(scope,caseId,id,A.validatePatch(p),admin,A.version(A.get(scope,caseId,id)));
const way=(id,type,value,preferred=false)=>({id,type,value,preferred,label:id});
const picture='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=';
const extras={tags:['Pflege','Notfall'],groups:['Netzwerk'],customFields:[{id:'f',label:'Sprache',type:'select',value:'Deutsch',options:['Deutsch','Englisch']}],imageData:picture,imageKind:'logo'};
test('Gemeinsame Zusatzfelder validieren Struktur, Datumswerte, Auswahl und ausschließlich eingebettete Rasterbilder',()=>{
 assert.deepEqual(D.labels([' Pflege ','pflege','Notfall']),['Pflege','Notfall']);assert.deepEqual(A.validatePatch(extras),extras);
 for(const data of [{tags:'x'},{customFields:[{id:'a',label:'Datum',type:'date',value:'2026-02-31'}]},{customFields:[{id:'a',label:'Auswahl',type:'select',value:'X',options:['A']}]},{imageData:'https://example.org/picture.jpg'},{imageData:'data:image/svg+xml;base64,PHN2Zz4='},{imageData:picture+'x'}])assert.throws(()=>A.validatePatch(data));
 assert.equal(D.customFields([{id:'n',label:'Zahl',type:'number',value:'12,5'}])[0].value,'12,5');
});
test('Weitere Kontaktweg-Arten sind keine Rufnummern; Links lassen keine aktiven oder fremden Protokolle zu',()=>{
 const ways=[way('web','website','https://example.org'),way('portal','portal','https://portal.example.org/path'),way('chat','messenger','@pflege'),way('other','other','Postfach Kennung')];assert.equal(T.ways(ways).length,4);assert.equal(T.withWays({contactWays:ways}).website,undefined);
 for(const value of ['javascript:alert(1)','file:///etc/passwd','https://user:pass@example.org','data:text/html,abc'])assert.throws(()=>T.ways([way('bad','website',value)]));
 assert.equal(T.duplicates({contactWays:[way('a','website','https://example.org/123456')]},[{institution:'Anderer',phone:'123456'}]).length,0);
 const native=P.native(P.profile({institution:'W',contactWays:ways}),'google');assert.deepEqual(native.phoneNumbers,[]);
});
test('vCard erhält alle neuen Angaben, Ansprechpartner-Webseiten sowie Standard-URL, CATEGORIES und LOGO',()=>{
 const contact={institution:'Test',...extras,contactWays:[way('portal','portal','https://portal.example.org',true),way('chat','messenger','@pflege')],people:[{id:'p',name:'Person',contactWays:[way('web','website','https://example.org')]}]};
 const text=V.stringify(contact),round=V.parse(text)[0];for(const k of Object.keys(extras))assert.deepEqual(round[k],extras[k]);assert.deepEqual(round.contactWays,contact.contactWays);assert.deepEqual(round.people[0].contactWays,contact.people[0].contactWays);
 const standard=V.parse(text.replace(/\r\n[ \t]/g,'').split(/\r?\n/).filter(l=>!l.startsWith('X-BETREUUNGSBUERO-DATA:')).join('\r\n'))[0];assert.deepEqual(standard.tags,extras.tags);assert.equal(standard.imageData,picture);assert.equal(standard.imageKind,'logo');assert.equal(standard.contactWays[0].type,'portal');assert.equal(standard.contactWays[0].preferred,true);assert.equal(standard.people[0].contactWays[0].type,'website');
});
test('Favoriten sind persönlich; Nutzung löschen erhält Favoriten; andere Benutzer erhalten keine Nutzungsliste',()=>{
 create('personal');const input={scope:'office',id:'personal'};O.save({...input,action:'favorite',value:true},reader);O.save({...input,action:'used'},reader);assert.equal(O.preferences(reader).personal[0].favorite,1);assert.ok(O.preferences(reader).personal[0].lastUsedAt);assert.equal(O.preferences(admin).personal.length,0);O.clearRecent(reader);assert.equal(O.preferences(reader).personal[0].lastUsedAt,'');assert.equal(O.preferences(reader).personal[0].favorite,1);
});
test('Fallfavoriten verlangen Schreibrecht und erscheinen nur für berechtigte Benutzer',()=>{
 create('local',{},'case','a');assert.throws(()=>O.save({scope:'case',caseId:'a',id:'local',action:'caseFavorite',value:true},reader));O.save({scope:'case',caseId:'a',id:'local',action:'caseFavorite',value:true},admin);assert.equal(O.preferences(reader).cases.length,0);assert.equal(O.preferences(admin).cases.length,1);
});
test('Zentralisierung erhält persönliche Favoriten; neue Felder propagieren ohne Fallnummern zu überschreiben',()=>{
 create('promote',{customerNumber:'0001'},'case','a');O.save({scope:'case',caseId:'a',id:'promote',action:'favorite',value:true},admin);O.save({scope:'case',caseId:'a',id:'promote',action:'used'},admin);const assigned=A.assign({scope:'case',caseId:'a',id:'promote',targetCaseId:'b',customerNumber:'0002'},admin);patch(assigned.centralId,extras);const p=O.preferences(admin).personal.find(x=>x.id===assigned.centralId);assert.equal(p.scope,'office');assert.ok(p.lastUsedAt);for(const r of A.linked(assigned.centralId)){assert.deepEqual(A.data(r).customFields,extras.customFields);assert.deepEqual(A.data(r).tags,extras.tags);assert.equal(A.data(r).imageData,picture)}assert.equal(A.data(A.get('case','a','promote')).customerNumber,'0001');assert.equal(A.data(A.get('case','b',assigned.assignment.contactId)).customerNumber,'0002');assert.ok(A.details('office','',assigned.centralId,admin).history.some(h=>h.changes.imageData));
});
test('Nutzungshistorie ist begrenzt und persönliche Favoriten bleiben erhalten',()=>{
 for(let i=0;i<105;i++){create('recent-'+i);O.save({scope:'office',id:'recent-'+i,action:'used'},admin)}assert.equal(O.preferences(admin).personal.filter(x=>x.lastUsedAt).length,100);assert.ok(O.preferences(admin).personal.some(x=>x.favorite));
});
test('Datenqualität prüft mehrere Profile und nur sichtbare Fälle, ohne zentrale Kontakte mehrfach zu zählen',()=>{
 create('hidden-quality',{email:'ungültig'},'case','a');create('own-quality',{email:'falsch',street:'Weg',postal:'12'},'case','b');const q=O.quality({},reader);assert.ok(q.items.some(x=>x.id==='own-quality'));assert.ok(!q.items.some(x=>x.id==='hidden-quality'));const issues=D.quality({institution:'X',people:[{name:'A',contactWays:[way('email','email','valid@example.org')]}],street:'Weg',postal:'123'});assert.ok(!issues.some(x=>x.code==='channels'));assert.ok(issues.some(x=>x.code==='address'));assert.ok(issues.some(x=>x.code==='postal'));
 assert.equal(D.quality({institution:'US',street:'Main',house:'12',postal:'12345-6789',country:'USA',city:'Place',email:'a@example.org'}).length,0);
});
test('Zentrale Synchronisationsübersicht schützt private Konten und fremde Fälle und enthält Fehler und Pausen',()=>{
 db.prepare("INSERT INTO calendar_connections(id,provider,display_name,enabled,owner_user_id) VALUES('private','google','Privat',1,1),('reader','google','Leser',0,2)").run();create('sync-office');create('sync-hidden',{},'case','a');create('sync-own',{},'case','b');
 const insert=db.prepare('INSERT INTO addressbook_sync_bindings(id,scope,case_id,contact_id,connection_id,owner_user_id,status,error,last_synced_at) VALUES(?,?,?,?,?,?,?,?,?)');insert.run('one','office','','sync-office','private',1,'conflict','Konflikt','2026-09-12');insert.run('two','case','a','sync-hidden','reader',2,'error','Geheim','');insert.run('three','case','b','sync-own','reader',2,'synced','','2026-09-12');
 const q=S.overview({},reader);assert.equal(q.total,1);assert.equal(q.items[0].contactId,'sync-own');assert.equal(q.counts.paused,1);assert.equal(q.items[0].canManage,false);assert.equal(S.overview({},admin).total,3);
});
test('Endgültige Löschung prüft alle Fälle atomar und entfernt Wiederherstellung, Favoriten und Abgleich',()=>{
 create('purge',extras,'case','c');O.save({scope:'case',caseId:'c',id:'purge',action:'caseFavorite',value:true},editor);const assigned=A.assign({scope:'case',caseId:'c',id:'purge',targetCaseId:'a'},admin),id=assigned.centralId;O.save({scope:'office',id,action:'favorite',value:true},admin);const removed=Trash.remove({scope:'office',id},admin);assert.throws(()=>Trash.purge({ids:[removed.trashId],confirm:true},editor));assert.ok(Trash.list(admin).items.some(i=>i.id===removed.trashId));assert.throws(()=>Trash.purge({ids:[removed.trashId]},admin));const r=Trash.purge({ids:[removed.trashId],confirm:true},admin);assert.equal(r.deleted,1);assert.equal(O.preferences(admin).personal.some(p=>p.id===id),false);assert.equal(db.prepare('SELECT 1 FROM addressbook_case_favorites WHERE contact_id=?').get('purge'),undefined);assert.throws(()=>Trash.restore({id:removed.trashId},admin));assert.equal(Trash.purge({ids:[removed.trashId],confirm:true},admin).deleted,0);
});
test('Wiederhergestellte Kontakte und laufende Abgleiche können nicht endgültig gelöscht werden',()=>{
 create('race');const deleted=Trash.remove({scope:'office',id:'race'},admin);Trash.restore({id:deleted.trashId},admin);assert.throws(()=>Trash.purge({ids:[deleted.trashId],confirm:true},admin),e=>e.status===409);assert.ok(A.get('office','','race'));const again=Trash.remove({scope:'office',id:'race'},admin);db.prepare("INSERT INTO addressbook_sync_bindings(id,scope,contact_id,connection_id,owner_user_id,lock_until) VALUES('race-binding','office','race','private',1,?)").run(Date.now()+10000);assert.throws(()=>Trash.purge({ids:[again.trashId],confirm:true},admin),e=>e.status===409);db.prepare("UPDATE addressbook_sync_bindings SET lock_until=0 WHERE id='race-binding'").run();Trash.purge({ids:[again.trashId],confirm:true},admin);assert.equal(db.prepare("SELECT 1 FROM addressbook_sync_bindings WHERE id='race-binding'").get(),undefined);assert.equal(db.prepare("SELECT 1 FROM addressbook_trash WHERE contact_id='race'").get(),undefined);
});
test('Zusammenführen erhält Schlagwörter, Gruppen, Zusatzfelder und weitere Kontaktwege',()=>{
 create('merge1',{tags:['A'],groups:['Eins'],customFields:extras.customFields,contactWays:[way('web','website','https://one.example',true)]},'case','a');create('merge2',{tags:['B'],groups:['Zwei'],customFields:[{id:'f2',label:'Zusatz',type:'text',value:'Wert',options:[]}],contactWays:[way('web2','website','https://two.example',true)]},'case','a');O.save({scope:'case',caseId:'a',id:'merge2',action:'favorite',value:true},admin);O.save({scope:'case',caseId:'a',id:'merge2',action:'caseFavorite',value:true},admin);const M=require('../src/modules/contacts/addressbook-merge');M.merge({caseId:'a',operationId:'merge-org',groups:[{ids:['merge1','merge2'],survivorId:'merge1',versions:Object.fromEntries(['merge1','merge2'].map(id=>[id,A.version(A.get('case','a',id))]))}]},admin);const r=A.data(A.get('case','a','merge1'));assert.deepEqual(r.tags,['A','B']);assert.deepEqual(r.groups,['Eins','Zwei']);assert.equal(r.customFields.length,2);assert.equal(r.contactWays.length,2);assert.equal(r.contactWays.filter(w=>w.preferred).length,1);assert.ok(O.preferences(admin).personal.find(p=>p.id==='merge1').favorite);assert.ok(O.preferences(admin).cases.find(p=>p.id==='merge1'));
});
test('Gespeicherte Ansichten und Modulsicherungen berücksichtigen die Erweiterungen',()=>{
 const views=require('../src/modules/contacts/addressbook-views');views.save({id:'new',label:'Pflegefavoriten',filters:{quick:'favorite',tag:'Pflege',group:'Netzwerk'},version:0},admin);assert.equal(views.list(admin).views[0].filters.quick,'favorite');const b=require('../src/modules/backup/portable-data'),data=b.moduleData(db);assert.ok(data.addressbookPreferences.length);assert.ok(data.addressbookCaseFavorites.length);assert.ok(b.restoreDefinitions('module').some(x=>x.table==='addressbook_preferences'));
});
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true})});
