'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
const script=html.split('<script id="vermoegen-script-v1">')[1].split('</script>')[0];
function source(a,b){const i=script.indexOf(a),j=script.indexOf(b,i);assert.ok(i>=0&&j>i,a);return script.slice(i,j)}
const row=(id,extra={})=>({id,category:'Girokonto',details:'Guthaben',institution:'Musterbank',amount:'100',...extra});
function context(assets={}){const c={window:{},state:{caseData:{assets:{begin:[],end:[],debtsBegin:[],debtsEnd:[],...assets}}},VAM:{period:'begin',kind:'all',category:'all',institution:'all',source:'all',sort:'original',query:'',caseId:'a'},VAM_KEYS:['begin','end','debtsBegin','debtsEnd'],vamCanWrite:()=>true,vamCase:()=> 'a',num:v=>Number(String(v).replace(',','.'))||0,nid:()=> 'new-id',saveState:()=>c.saves++,refreshVaIndicator(){},saves:0};vm.createContext(c);vm.runInContext(source('  function A(){','  function materialize(){')+source('  function vamDebt(','  function vamName(')+source('  function vamOrigin(','  function vamMount(')+source('  function vamCommit(','  function vamSave('),c);c.VAM.caseData=c.state.caseData;return c}
test('Vermögensaufstellung: Anfang und Abschluss verwenden alle vier Bereiche und behalten gleiche IDs getrennt',()=>{const c=context({begin:[row('same')],end:[row('same',{amount:'90'})],debtsBegin:[row('debt',{amount:'20'})],debtsEnd:[row('debt',{amount:'10'})]});assert.deepEqual(Array.from(c.vamRows(),x=>[x.key,x.entry.amount]),[['begin','100'],['debtsBegin','20']]);c.VAM.period='end';assert.deepEqual(Array.from(c.vamRows(),x=>[x.key,x.entry.amount]),[['end','90'],['debtsEnd','10']])});
test('Vermögensaufstellung: Herkunft, Kategorie, Institut, Position und Volltext kombinieren sich',()=>{const c=context({begin:[row('asset')],debtsBegin:[row('manual'),row('source',{source:'schuldenregulierung',details:'Vollständiger Zweck'})]});Object.assign(c.VAM,{kind:'debts',source:'sr',category:'Girokonto',institution:'Musterbank',query:'VOLLSTÄNDIGER'});assert.deepEqual(Array.from(c.vamRows(),x=>x.entry.id),['source']);c.VAM.institution='Andere Bank';assert.equal(c.vamRows().length,0)});
test('Vermögensaufstellung: Sortierung verändert die zugrunde liegende Reihenfolge nicht',()=>{const c=context({begin:[row('a',{amount:'10',category:'Z'}),row('b',{amount:'20',category:'A'})]});c.VAM.sort='amount';assert.equal(c.vamRows()[0].entry.id,'b');c.VAM.sort='category';assert.equal(c.vamRows()[0].entry.id,'b');assert.equal(c.state.caseData.assets.begin[0].id,'a')});
test('Vermögensaufstellung: neue Position wird genau einmal im ausgewählten Bereich gespeichert',()=>{for(const [kind,period,key] of [['assets','begin','begin'],['assets','end','end'],['debts','begin','debtsBegin'],['debts','end','debtsEnd']]){const c=context();const result=c.vamCommit({kind,period,category:'Neu',details:'Alle Angaben',institution:'Institut',amount:'12.34'});assert.equal(result.key,key);assert.equal(c.state.caseData.assets[key][0].amount,'12.34');assert.equal(c.state.caseData.assets[key][0].details,'Alle Angaben');assert.equal(c.saves,1);assert.equal(Object.values(c.state.caseData.assets).flat().length,1)}});
test('Vermögensaufstellung: Bearbeitung erhält Metadaten, ID und den unabhängigen Abschlusswert',()=>{const e=row('same',{sourceRef:'bank:entry',custom:{keep:true}}),c=context({begin:[e],end:[row('same',{amount:'90'})]});Object.assign(c.VAM,{key:'begin',id:e.id,baseline:JSON.stringify(e)});c.vamCommit({...e,amount:'105.25'});assert.equal(e.id,'same');assert.equal(e.sourceRef,'bank:entry');assert.equal(e.custom.keep,true);assert.equal(c.state.caseData.assets.end[0].amount,'90');assert.equal(c.saves,1)});
test('Vermögensaufstellung: entfallene oder fremd geänderte Position wird nicht mit einem älteren Entwurf überschrieben',()=>{for(const change of ['delete','edit','reload','case']){const e=row('a'),c=context({begin:[e]});Object.assign(c.VAM,{key:'begin',id:e.id,baseline:JSON.stringify(e)});if(change==='delete')c.state.caseData.assets.begin=[];if(change==='edit')e.details='Remote';if(change==='reload')c.state.caseData={assets:c.state.caseData.assets};if(change==='case')c.vamCase=()=> 'other';assert.throws(()=>c.vamCommit({...e,amount:'999'}));assert.equal(e.amount,'100');assert.equal(c.saves,0)}});
test('Vermögensaufstellung: Leseberechtigte und Schulden-Spiegelungen werden vor jeder Mutation abgewiesen',()=>{for(const readonly of [true,false]){const e=row('a',{source:'schuldenregulierung'}),c=context({debtsBegin:[e]});if(readonly)c.vamCanWrite=()=>false;Object.assign(c.VAM,{key:'debtsBegin',id:e.id,baseline:JSON.stringify(e)});assert.throws(()=>c.vamCommit({...e,amount:'999'}));assert.equal(e.amount,'100');assert.equal(c.saves,0)}});
test('Vermögensaufstellung: Speicherfehler stellt den vorherigen Stand wieder her und entfernt keine fremden Werte',()=>{for(const edit of [true,false]){const e={id:'a',category:'Girokonto',amount:'100'},c=context({begin:[e]});if(edit)Object.assign(c.VAM,{key:'begin',id:e.id,baseline:JSON.stringify(e)});c.saveState=()=>{throw new Error('Speicher nicht erreichbar')};assert.throws(()=>c.vamCommit({kind:'assets',period:'begin',category:'Geändert',amount:'200'}),/Speicher/);assert.equal(c.state.caseData.assets.begin.length,1);assert.equal(e.category,'Girokonto');assert.equal(e.amount,'100');assert.equal(Object.hasOwn(e,'details'),false);assert.equal(Object.hasOwn(e,'institution'),false)}});
test('Vermögensaufstellung: vorhandene offene Werte und negative Zahlen bleiben möglich, ungültige Angaben schreiben nichts',()=>{const c=context();c.vamCommit({kind:'assets',period:'begin',amount:''});assert.equal(c.state.caseData.assets.begin[0].amount,'');const negative=context();negative.vamCommit({kind:'assets',period:'end',amount:'-5.25'});assert.equal(negative.state.caseData.assets.end[0].amount,'-5.25');for(const payload of [{kind:'wrong',period:'begin',amount:'10'},{kind:'assets',period:'wrong',amount:'10'},{kind:'assets',period:'begin',amount:'NaN'}]){const invalid=context();assert.throws(()=>invalid.vamCommit(payload));assert.equal(invalid.saves,0)}});
test('Modul-Fallwechsler: Berichtsübergabe gibt ausschließlich den gewünschten Rücksprung frei',()=>{const s=html.split('<script id="module-case-switcher-v160">')[1].split('</script>')[0],a=s.indexOf('window.__moduleCaseSwitchKeep=function'),b=s.indexOf('window.__moduleCaseSwitchRestore=function',a),c={window:{},reg:{assets:{ret:'original',switching:false},livelihood:{ret:'other',switching:false}}};vm.createContext(c);vm.runInContext(s.slice(a,b),c);assert.equal(c.window.__moduleCaseSwitchKeep('assets'),true);assert.equal(c.reg.assets.ret,null);assert.equal(c.reg.livelihood.ret,'other');c.reg.assets={ret:'busy',switching:true};assert.equal(c.window.__moduleCaseSwitchKeep('assets'),false);assert.equal(c.reg.assets.ret,'busy');assert.equal(c.window.__moduleCaseSwitchKeep('missing'),false)});

function accountingContext(assets,accounts=[]){const c={window:{},state:{caseData:{assets},accounting:{assets:[{category:'Bargeld und Bankguthaben',description:'',start:null,end:null}],liabilities:[],accounts}},accReport:()=>c.state.accounting,accNum:v=>v==null||v===''?null:Number(v),accId:()=> 'imported',accLast4:()=> '1234',accSave(){},accRender(){},accToast(){}};vm.createContext(c);for(const [a,b] of [['function accSyncBankAsset(){','function accRenumber(){'],['function accAddAssetsFromMaster(){','function accAddAccount(){']]){const i=html.indexOf(a);vm.runInContext(html.slice(i,html.indexOf(b,i)),c)}c.accRenumber=()=>c.accSyncBankAsset();return c}
test('Rechnungslegung: importiertes Bargeld behält beide Werte auch bei erneuter Kontoberechnung',()=>{for(const category of ['Bargeld','Bargeld und Bankguthaben']){const c=accountingContext({begin:[row('begin',{category,amount:'500'})],end:[row('end',{category,amount:'420'})],debtsBegin:[],debtsEnd:[]},[{openingBalance:10,closingBalance:8,name:'Konto'}]);c.accAddAssetsFromMaster();c.accSyncBankAsset();const e=c.state.accounting.assets[0];assert.equal(e.start,500);assert.equal(e.end,420);assert.equal(e.description,'Guthaben, Musterbank');assert.equal(e.source,'vermoegensaufstellung');c.accAddAssetsFromMaster();assert.equal(c.state.accounting.assets.length,1)}});
test('Rechnungslegung: die vorgesehene Kontosumme bleibt automatisch und auf Cent gerundet',()=>{const c=accountingContext({},[{openingBalance:0.1,closingBalance:0.2,name:'A'},{openingBalance:0.2,closingBalance:0.4,name:'B'}]);c.accSyncBankAsset();const e=c.state.accounting.assets[0];assert.equal(e.start,0.3);assert.equal(e.end,0.6);assert.equal(e.autoFromAccounts,true);assert.ok(e.description.includes('A 1234'));assert.ok(e.description.includes('B 1234'))});
