'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8'),script=html.split('<script id="lebensunterhalt-script-v1">')[1].split('</script>')[0];
function source(a,b){const i=script.indexOf(a),j=script.indexOf(b,i);assert.ok(i>=0&&j>i,a);return script.slice(i,j)}
const row=(id,extra={})=>({id,category:'Rente',description:'Altersrente',provider:'Rentenkasse',frequency:'monatlich',total:'1200',monthly:'100',...extra});
function context(livelihood={income:[],expenses:[]},benefits=[]){const c={window:{},state:{caseData:{livelihood,benefits},reports:{keep:{value:1}}},LUM:{tab:'income',category:'all',frequency:'all',status:'all',origin:'all',sort:'original',query:'',caseId:'a',key:'income',id:''},lumCanWrite:()=>true,lumCase:()=> 'a',lumName:()=> 'Test',nid:()=> 'new',saveState:()=>c.saves++,luRefreshInd(){},saves:0,num:v=>parseFloat(String(v??'').replace(',','.'))||0};vm.createContext(c);vm.runInContext(source('  function L(){','  function materialize(){')+source('  function luNorm(','  function luLoadBenefitsIntoIncome(')+source('  function lumEditable(','  function lumName(')+source('  function lumOrigin(','  function lumValue(')+source('  function lumRows(','  function lumSummary(')+source('  function lumSnapshot(','  function lumError(')+source('  function lumAnalysisCurrent(','  async function lumAnalyze('),c);c.LUM.caseData=c.state.caseData;c.LUM.benefitsBaseline=JSON.stringify({income:livelihood.income,benefits});return c}
function edit(c,e,key='income'){Object.assign(c.LUM,{id:e.id,key,baseline:JSON.stringify(e)})}
test('Lebensunterhalt: Bereich, Volltext, Kategorie, Intervall, Status und Herkunft kombinieren sich',()=>{const c=context({income:[row('a'),row('b',{category:'Sozialleistung',description:'Grundsicherung',source:'stammdaten',status:'bewilligt'})],expenses:[row('sr',{source:'schuldenregulierung'})]});Object.assign(c.LUM,{category:'Sozialleistung',frequency:'monatlich',status:'bewilligt',origin:'Stammdaten',query:'GRUNDSICHERUNG'});assert.deepEqual(Array.from(c.lumRows(),e=>e.id),['b']);c.LUM.tab='expenses';assert.equal(c.lumRows().length,0)});
test('Lebensunterhalt: Sortieren verändert die gespeicherte Reihenfolge nicht',()=>{const c=context({income:[row('a'),row('b',{monthly:'300'})],expenses:[]});c.LUM.sort='amount';assert.equal(c.lumRows()[0].id,'b');assert.equal(c.state.caseData.livelihood.income[0].id,'a')});
test('Lebensunterhalt: Einnahme wird mit allen Feldern gespeichert und als Leistung verknüpft',()=>{const c=context();const r=c.lumCommit({kind:'income',category:'Rente',description:'Rentenbezug',party:'Träger',frequency:'jährlich',total:'1200',monthly:'100'});assert.equal(r.key,'income');const e=c.state.caseData.livelihood.income[0];assert.equal(e.provider,'Träger');assert.equal(e.monthly,'100');assert.equal(e.__syncBenefit,true);assert.equal(c.state.caseData.benefits[0].monthly,100);assert.equal(c.saves,1)});
test('Lebensunterhalt: Ausgaben speichern Status und Ratenende ohne fremde Leistungen zu ändern',()=>{const b={benefit:'Vorhanden'},c=context(undefined,[b]);c.lumCommit({kind:'expenses',category:'Miete',party:'Vermieter',frequency:'monatlich',total:'600',monthly:'600',status:'laufend',ratenzahlungBis:'2027-12-31'});const e=c.state.caseData.livelihood.expenses[0];assert.equal(e.creditor,'Vermieter');assert.equal(e.ratenzahlungBis,'2027-12-31');assert.equal(e.status,'laufend');assert.equal(c.state.caseData.benefits[0],b)});
test('Lebensunterhalt: Nullbeträge ersetzen alte Leistungsbeträge und werden nicht als leer geladen',()=>{const e=row('a'),c=context({income:[e],expenses:[]});c.luSyncIncomeToBenefits();edit(c,e);c.LUM.benefitsBaseline=JSON.stringify({income:c.state.caseData.livelihood.income,benefits:c.state.caseData.benefits});c.lumCommit({...e,party:e.provider,monthly:'0',total:'0'});assert.equal(c.state.caseData.benefits[0].monthly,0);assert.equal(c.state.caseData.benefits[0].total,0);const imported=c.luIncomeFromBenefit(c.state.caseData.benefits[0]);assert.equal(imported.monthly,0);assert.equal(imported.total,0)});
test('Lebensunterhalt: Bearbeitung erhält Kennung, Aktenzeichen und unbekannte Metadaten',()=>{const e=row('a',{fileNumber:'AZ-1',custom:{keep:true}}),c=context({income:[e],expenses:[]});edit(c,e);c.lumCommit({...e,party:e.provider,monthly:'125'});assert.equal(e.id,'a');assert.equal(e.fileNumber,'AZ-1');assert.equal(e.custom.keep,true);assert.equal(e.monthly,'125')});
test('Lebensunterhalt: Fall-, Daten-, Posten- und Leistungsänderungen verhindern das Überschreiben',()=>{for(const change of ['case','reload','entry','benefit','delete']){const e=row('a'),c=context({income:[e],expenses:[]});edit(c,e);if(change==='case')c.lumCase=()=> 'b';if(change==='reload')c.state.caseData={...c.state.caseData};if(change==='entry')e.monthly='900';if(change==='benefit')c.state.caseData.benefits.push({benefit:'Neu'});if(change==='delete')c.state.caseData.livelihood.income=[];assert.throws(()=>c.lumCommit({...e,party:e.provider,monthly:'200'}));assert.equal(c.saves,0)}});
test('Lebensunterhalt: Leserechte und gespiegelt gepflegte Raten werden vor Speichern geprüft',()=>{for(const readonly of [false,true]){const e=row('a',{source:readonly?'manual':'schuldenregulierung'}),c=context({income:[],expenses:[e]});edit(c,e,'expenses');if(readonly)c.lumCanWrite=()=>false;assert.throws(()=>c.lumCommit({...e,party:'Gläubiger',monthly:'200'}));assert.equal(e.monthly,'100');assert.equal(c.saves,0)}});
test('Lebensunterhalt: Speicherfehler stellt Posten, verknüpfte Leistungen und Berichte gemeinsam wieder her',()=>{const e=row('a'),c=context({income:[e],expenses:[]});edit(c,e);const before=JSON.stringify(c.state);c.saveState=()=>{throw new Error('Speicherfehler')};assert.throws(()=>c.lumCommit({...e,party:e.provider,monthly:'200'}),/Speicherfehler/);assert.equal(JSON.stringify(c.state),before)});
test('Lebensunterhalt: Auswertung bleibt an die ursprüngliche Fallinstanz und Schreibberechtigung gebunden',()=>{const c=context(),ctx={caseId:'a',caseData:c.state.caseData};assert.equal(c.lumAnalysisCurrent(ctx),true);c.state.caseData={...c.state.caseData};assert.equal(c.lumAnalysisCurrent(ctx),false);c.state.caseData=ctx.caseData;c.lumCanWrite=()=>false;assert.equal(c.lumAnalysisCurrent(ctx),false)});
