/* Execute the shipped navigation policy: directional hysteresis, keyboard priority and
 * bounded DOM access. Synthetic geometry covers both visual and layout viewport resizing. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),test=require('node:test'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
function source(name){const a=html.indexOf('function '+name+'(');assert.ok(a>=0);let depth=0;for(let i=html.indexOf('{',a);i<html.length;i++){if(html[i]==='{')depth++;else if(html[i]==='}'&&!--depth)return html.slice(a,i+1)}throw Error(name)}
function element(extra={}){const attrs={},classes=new Set();return {hidden:false,inert:false,classes,style:{setProperty(k,v){this[k]=v}},classList:{contains:k=>classes.has(k),add:k=>classes.add(k),remove:k=>classes.delete(k),toggle(k,v){v?v=classes.add(k):classes.delete(k)}},getAttribute:k=>attrs[k],setAttribute:(k,v)=>attrs[k]=v,contains:e=>e.owner===this,matches:()=>false,closest:()=>null,...extra}}
function fixture(){
 const body=element(),view=element({dataset:{mobileScreen:'list'}}),scroller=element({scrollHeight:2400,clientHeight:600}),inputScroller=element({scrollHeight:900,clientHeight:100,matches:()=>true});
 body.querySelector=()=>view;body.contains=e=>e===scroller||e===inputScroller;
 const root=element({scrollHeight:3000}),modal=element(),shell=element(),timers=new Map();let now=100000,sequence=0;
 const state={mobile:true,chat:false,probeCalls:0};
 const ctx={window:{innerWidth:390,innerHeight:844,scrollY:0,visualViewport:{height:844,width:390,scale:1,offsetTop:0},setTimeout:(fn,delay)=>{const id=++sequence;timers.set(id,{fn,at:now+delay});return id}},clearTimeout:id=>timers.delete(id),document:{documentElement:root,activeElement:null,body:element(),getElementById:id=>({modal,modalBody:body,uchatDock:state.chat?body:null,workspace:body,startPage:body})[id]},shell,sheet:null,isMobileActive:()=>state.mobile,chatState:()=>({open:state.chat}),Date:{now:()=>now},state};
 const policy=html.slice(html.indexOf('  // Gemeinsame Navigationsregel:'),html.indexOf('\n  window.__mobileUI = Object.freeze'));
 vm.createContext(ctx);vm.runInContext('let shellToggleAt=0,scrollProbe=null,activeMobileActionId="tasks";\n'+policy+'\n'+source('computeScrollProbe')+'\n'+source('handleScroll')+'\nconst computeOriginal=computeScrollProbe;computeScrollProbe=()=>{state.probeCalls++;return computeOriginal()};this.scroll=handleScroll;this.sync=syncMobileViewport;this.reveal=revealMobileNavigation;this.viewSync=syncMobileNavigationView;',ctx);
 const tick=ms=>{now+=ms;for(const [id,t] of [...timers])if(t.at<=now){timers.delete(id);t.fn()}};
 const scroll=y=>{scroller.scrollTop=y;ctx.scroll(scroller,y)},hidden=()=>shell.classes.has('is-hidden');
 return {ctx,root,shell,state,view,scroller,inputScroller,modal,tick,scroll,hidden,hide(){scroll(0);scroll(100);scroll(150);tick(300)}};
}
test('Stetiges Scrollen in kleinen Schritten blendet aus; keine Selektorkaskade je Ereignis',()=>{const f=fixture();for(let y=0;y<=300;y+=3)f.scroll(y);assert.equal(f.hidden(),true);assert.equal(f.state.probeCalls,1);f.scroll(0);assert.equal(f.hidden(),false)});
test('Kleine Gegenbewegungen flackern nicht, bewusster Richtungswechsel blendet wieder ein',()=>{const f=fixture();f.hide();for(const y of [147,150,146,149])f.scroll(y);f.tick(300);assert.equal(f.hidden(),true);f.scroll(125);f.tick(300);assert.equal(f.hidden(),false)});
test('Ein schneller abgeschlossener Richtungswechsel wird nach der Sperrfrist übernommen',()=>{const f=fixture();f.scroll(0);f.scroll(100);f.scroll(160);f.tick(10);f.scroll(130);assert.equal(f.hidden(),true);f.tick(250);assert.equal(f.hidden(),false)});
test('Der Seitenanfang gewinnt sofort gegen die Sperrfrist',()=>{const f=fixture();f.hide();f.scroll(0);assert.equal(f.hidden(),false);assert.equal(f.shell.inert,false);assert.equal(f.shell.getAttribute('aria-hidden'),'false')});
test('Fremde Hintergrundroller, Eingabefelder und horizontale Bewegung schalten nicht um',()=>{const f=fixture();const other=element({scrollHeight:2400,clientHeight:600});f.ctx.scroll(other,200);f.ctx.scroll(other,500);f.ctx.scroll(f.inputScroller,200);f.ctx.scroll(f.inputScroller,500);f.scroll(100);f.scroll(100);assert.equal(f.hidden(),false)});
test('Neue Ansicht zeigt die Navigation und verwirft einen ausstehenden Richtungswechsel',()=>{const f=fixture();f.hide();f.scroll(120);f.view.dataset.mobileScreen='form';f.ctx.viewSync();f.tick(300);assert.equal(f.hidden(),false)});
test('Modal- und Chatwechsel erneuern die Scrollprüfung nur einmal',()=>{const f=fixture();f.scroll(0);f.scroll(150);assert.equal(f.state.probeCalls,1);f.modal.classes.add('hidden');f.ctx.scroll(f.ctx.window,100);assert.equal(f.state.probeCalls,2);f.ctx.scroll(f.ctx.window,200);assert.equal(f.state.probeCalls,2);f.state.chat=true;f.scroll(250);assert.equal(f.state.probeCalls,3)});
test('Tastatur hat Vorrang vor Scrollen, Seitenanfang und Menüöffnung; Schließen zeigt wieder an',()=>{const f=fixture();f.ctx.sync();f.ctx.document.activeElement={tagName:'TEXTAREA'};f.ctx.window.visualViewport.height=500;f.ctx.sync();assert.equal(f.root.classes.has('mobile-keyboard-open'),true);f.scroll(0);f.ctx.reveal();assert.equal(f.hidden(),true);assert.equal(f.shell.inert,true);f.ctx.window.visualViewport.height=844;f.ctx.sync();assert.equal(f.hidden(),false);assert.equal(f.root.classes.has('mobile-keyboard-open'),false)});
test('Android mit verkleinertem innerHeight bleibt über die gemerkte Höhe erkennbar',()=>{const f=fixture();f.ctx.sync();f.ctx.document.activeElement={tagName:'INPUT',type:'text'};f.ctx.window.innerHeight=500;f.ctx.window.visualViewport.height=500;f.ctx.sync();assert.equal(f.hidden(),true)});
test('Browserleisten, Pinch-Zoom und eine Hardwaretastatur sind keine Bildschirmtastatur',()=>{const f=fixture();f.ctx.sync();f.ctx.window.visualViewport.height=760;f.ctx.sync();assert.equal(f.hidden(),false);f.ctx.document.activeElement={tagName:'INPUT',type:'text'};f.ctx.sync();assert.equal(f.hidden(),false);f.ctx.window.visualViewport.height=450;f.ctx.window.visualViewport.scale=1.8;f.ctx.sync();assert.equal(f.hidden(),false)});
test('Offene Auswahlblätter und Desktop werden nicht vom Scrollen umgeschaltet',()=>{const f=fixture();f.ctx.sheet=element();f.ctx.sheet.classes.add('is-open');f.scroll(0);f.scroll(200);f.scroll(400);assert.equal(f.hidden(),false);f.ctx.sheet=null;f.state.mobile=false;f.scroll(500);assert.equal(f.hidden(),false)});
test('Navigation verschiebt ihre Leiste ohne Root-Has-Selektor und respektiert reduzierte Bewegung',()=>{assert.ok(!html.includes(':has(.mobile-online-shell.is-hidden)'));assert.match(html,/\[?prefers-reduced-motion:reduce[\s\S]*?#mobileOnlineShell#mobileOnlineShell/);const a=html.indexOf('html.mobile-online-active #mobileOnlineShell#mobileOnlineShell.is-hidden');const css=html.slice(a,html.indexOf('}',a));assert.ok(!/height:|padding:|margin:/.test(css));assert.match(html,/mobile-keyboard-open #mobileOnlineShell#mobileOnlineShell\{display:none!important/)});
