'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
const script=html.split('<script id="handkasse-script-v1">')[1].split('</script>')[0];
function source(a,b){const i=script.indexOf(a),j=script.indexOf(b,i);assert.ok(i>=0&&j>i,a);return script.slice(i,j)}
function context(entries=[]){const c={window:{},state:{caseData:{handkasse:entries}},HM:{caseId:'case-a',query:'',type:'all',category:'all',source:'all',sort:'newest'},hkJahr:'all',HK_INTERVALS:[[''],['weekly'],['biweekly'],['monthly'],['quarterly'],['yearly']],hmCase:()=> 'case-a',hmCanWrite:()=>true,num:v=>Number(v)||0,nid:()=> 'new',saveState:()=>c.saves++,hkMaterializeSeries:()=>c.series++,hkAutoDokuV168:e=>{c.doku.push(structuredClone(e));return Promise.resolve()},refreshHkIndicator(){},saves:0,series:0,doku:[]};vm.createContext(c);vm.runInContext(source('function hkData(){','function caseOpen(){')+source('function sorted(){','function hkAutoDokuV168(')+source('function hmEditable(','function hmN(')+source('function hmDate(','function hmMount(')+source('function hmCommit(','function hmSave('),c);c.hkPasst=e=>c.hkJahr==='all'||e.date.slice(0,4)===c.hkJahr;c.HM.caseData=c.state.caseData;return c}
const row=(id,extra={})=>({id,date:'2026-09-01',type:'ausgabe',amount:'10',recipient:'Mara',purpose:'Barbetrag',category:'Taschengeld',interval:'',...extra});
test('Handkasse: Jahres- und Suchfilter verändern laufende Salden einschließlich Vorjahresübertrag nicht',()=>{const c=context([row('carry',{date:'2025-12-31',type:'einnahme',amount:'100'}),row('a'),row('b',{amount:'20',category:'Gesundheit'})]);c.hkJahr='2026';c.HM.query='Gesundheit';const rows=c.hmVisibleRows();assert.equal(rows.length,1);assert.equal(rows[0].entry.id,'b');assert.equal(rows[0].balance,70);assert.equal(c.balance(),70)});
test('Handkasse: Sortierung, Art, Kategorie und Serien-/Schuldenherkunft kombinieren sich',()=>{const c=context([row('a'),row('template',{interval:'monthly'}),row('generated',{seriesId:'template',amount:'30'}),row('sr',{source:'schuldenregulierung'}),row('income',{type:'einnahme'})]);c.HM.source='series';c.HM.sort='amount';assert.deepEqual(Array.from(c.hmVisibleRows(),r=>r.entry.id),['generated','template']);c.HM.source='sr';assert.equal(c.hmVisibleRows()[0].entry.id,'sr');c.HM.source='all';c.HM.type='einnahme';assert.equal(c.hmVisibleRows()[0].entry.id,'income');assert.equal(c.hmOrigin(row('bank',{sourceRef:'bank:tx-1'})),'Banking')});
test('Handkasse: vollständiger neuer Datensatz wird einmal gespeichert und dokumentiert',()=>{const c=context();const e=c.hmCommit(row('ignored',{amount:'12.45'}));assert.equal(e.id,'new');assert.equal(c.state.caseData.handkasse.length,1);assert.equal(c.saves,1);assert.equal(c.series,1);assert.equal(c.doku.length,1);assert.equal(c.doku[0].purpose,'Barbetrag');assert.equal(c.doku[0].amount,'12.45')});
test('Handkasse: geänderte Vorlagen erhalten fremde Metadaten und setzen Seriencursor nur bei Datum/Intervall zurück',()=>{const e=row('a',{interval:'monthly',seriesLast:'2026-09-01',bankingLink:'keep'}),c=context([e]);c.HM.selected='a';c.HM.baseline=JSON.stringify(e);c.hmCommit({...e,purpose:'Geändert'});assert.equal(e.seriesLast,'2026-09-01');assert.equal(e.bankingLink,'keep');c.HM.baseline=JSON.stringify(e);c.hmCommit({...e,interval:'weekly'});assert.equal(e.seriesLast,undefined)});
test('Handkasse: Folgebuchungen behalten Serienkennung und werden nicht selbst zur Vorlage',()=>{const e=row('child',{seriesId:'parent'}),c=context([e]);c.HM.selected=e.id;c.HM.baseline=JSON.stringify(e);c.hmCommit({...e,amount:'25',interval:'monthly'});assert.equal(e.seriesId,'parent');assert.equal(e.interval,'');assert.equal(e.amount,'25')});
test('Handkasse: fremder Fall, fehlende Rechte und gespiegelte Schuldenzahlung werden vor jedem Schreibzugriff abgewiesen',()=>{for(const mode of ['case','rights','sr']){const e=row('a',mode==='sr'?{source:'schuldenregulierung'}:{}),c=context([e]);c.HM.selected='a';c.HM.baseline=JSON.stringify(e);if(mode==='case')c.hmCase=()=> 'other';if(mode==='rights')c.hmCanWrite=()=>false;assert.throws(()=>c.hmCommit({...e,amount:'99'}));assert.equal(e.amount,'10');assert.equal(c.saves,0);assert.equal(c.doku.length,0)}});
test('Handkasse: neu geladene Falldaten, entfernte oder konkurrierend bearbeitete Buchungen verlieren keine Änderungen',()=>{for(const mode of ['state','delete','edit']){const e=row('a'),c=context([e]);c.HM.selected='a';c.HM.baseline=JSON.stringify(e);if(mode==='state')c.state.caseData={handkasse:[e]};if(mode==='delete')c.state.caseData.handkasse=[];if(mode==='edit')e.purpose='Fremde Änderung';assert.throws(()=>c.hmCommit({...e,amount:'99'}));assert.equal(e.amount,'10');assert.equal(c.saves,0)}});
test('Handkasse: ungültige Beträge erreichen weder Kassenbuch noch AutoDoku',()=>{for(const amount of ['','-5','NaN','1x']){const c=context();assert.throws(()=>c.hmCommit(row('a',{amount})));assert.equal(c.state.caseData.handkasse.length,0);assert.equal(c.saves,0);assert.equal(c.doku.length,0)}});
