'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
const source=html.split('<script id="mileage-script-v1">')[1].split('</script>')[0];
function part(a,b){const i=source.indexOf(a),j=source.indexOf(b,i);assert.ok(i>=0&&j>i,a);return source.slice(i,j)}
const trip=(id,more={})=>({id,vehicleId:'v',fahrerUserId:1,datum:'07.09.2026',fahranlass:'Hausbesuch',caseLabel:'Mara',startAdresse:'Büro',zielAdresse:'Lindenstraße 8',kilometer:24,erstattungsbetrag:7.2,status:'entwurf',fahrerUnterschrift:'',...more});
function context(rows=[]){const c={window:{__currentUser:{id:1,isAdmin:false},isBueroLocalMode:()=>false,__appMode:'online',bueroLocal:{mileageTrips:rows.map(t=>({...t})),mileageVehicles:[{id:'v',ownerUserId:1,kennzeichen:'KO-A',status:'aktiv'}]},newBueroLocalId:()=> 'new',saveBueroLocal:()=>c.saves++},MM:{loaded:true,loading:false,error:'',seq:0,query:'',sort:'new',year:'',month:'',busy:false,driversReady:true,casesReady:true,form:null},mileageTrips:rows,mileageVehicles:[{id:'v',ownerUserId:1,kennzeichen:'KO-A',status:'aktiv'}],mileageCaseLabels:['Mara'],mileageDrivers:[{id:1,name:'Ada Beispiel'}],mileageUsers:[],mileageFilterVehicle:'',mileageFilterStatus:'',mileageFilterCase:'',mileageFilterFahrer:'',STATUS_LABELS:{entwurf:'Entwurf',eingereicht:'Eingereicht',geprueft:'Geprüft'},MILEAGE_LOCAL_RATE:.3,todayDE:()=> '08.09.2026',saves:0,mmOwned:()=>true,mmRender:()=>{},pruneMileageSelection:()=>{},toast:()=>{},Event,console};vm.createContext(c);vm.runInContext(part('function tripYear(','// Datum wird')+part('function mileageDriverLabel(','// Filter werden')+part('function vehicleLabel(','// Saubere')+part('function mmLocal(','function mmN(')+part('function mmPayload(','function mmRequestRender(')+part('async function mmCheck(','function mmCache(')+part('async function mmDistance(','async function mmCalendar('),c);return c}
test('Fahrtenfilter: Jahr, Monat, Fahrzeug, Fall, Fahrer, Status und Volltext kombinieren sich',()=>{const c=context([trip('a'),trip('b',{status:'geprueft'}),trip('c',{datum:'01.08.2026'})]);Object.assign(c.MM,{year:'2026',month:'09',query:'Lindenstraße'});Object.assign(c,{mileageFilterVehicle:'v',mileageFilterCase:'Mara',mileageFilterFahrer:'1',mileageFilterStatus:'entwurf'});assert.deepEqual(Array.from(c.mmRows(),t=>t.id),['a'])});
test('Fahrtenfilter: nicht zugeordnete Fahrten und importierte Fahrernamen bleiben auffindbar',()=>{const c=context([trip('a',{caseLabel:'',fahrerUserId:null,fahrerName:'Importierter Fahrer'}),trip('b')]);c.mileageFilterCase='__none__';c.MM.query='Importierter';assert.equal(c.mmRows().length,1);assert.equal(c.mmDriver(c.mmRows()[0]),'Importierter Fahrer')});
test('Chronologische Sortierung behandelt deutsches Datum und ISO-Datum gleichwertig',()=>{const c=context([trip('a',{datum:'31.01.2026'}),trip('b',{datum:'2026-02-02'}),trip('c',{datum:'03.02.2026'})]);assert.deepEqual(Array.from(c.mmRows(),t=>t.id),['c','b','a']);assert.equal(c.mileageTrips[0].id,'a')});
test('Auswertung summiert gespeicherte Erstattung einschließlich historischer und Nullbeträge',()=>{const c=context([trip('a',{erstattungsbetrag:9}),trip('b',{erstattungsbetrag:0,status:'eingereicht'})]);const sum=c.mmTotals(c.mmRows());assert.equal(sum.km,48);assert.equal(sum.amount,9);assert.equal(sum.eingereicht,1)});
test('Mitarbeitende bearbeiten nur eigene ungeprüfte Fahrten',()=>{const c=context();assert.equal(c.mmTripEditable(trip('a')),true);assert.equal(c.mmTripEditable(trip('b',{fahrerUserId:2})),false);assert.equal(c.mmTripEditable(trip('c',{status:'geprueft'})),false)});
test('Delegierte Prüfer bearbeiten Fahrten, erhalten aber keine fremde Fahrzeugverwaltung',()=>{const c=context();c.window.__currentUser.canApproveMileage=true;assert.equal(c.mmTripEditable(trip('a',{fahrerUserId:2,status:'ausgezahlt'})),true);assert.equal(c.mmVehicleEditable({id:'other',ownerUserId:2}),false)});
test('Leseschutz und fehlgeschlagener Abruf sperren Schreibaktionen',()=>{const c=context();c.window.__mwReadOnly=true;assert.equal(c.mmTripEditable(trip('a')),false);c.window.__mwReadOnly=false;c.MM.error='Abruf fehlgeschlagen';assert.equal(c.mmVehicleEditable(c.mileageVehicles[0]),false)});
function payloadContext(){const c=context(),values={mileageFormVehicle:'v',mileageFormDatum:'2026-09-07',mileageFormFahranlass:'Hausbesuch',mileageFormStart:'Büro',mileageFormZiel:'Ziel',mileageFormKm:'24',mileageFormCaseLabel:'Mara',mileageFormFahrer:'1'};c.MM.screen='tripForm';c.MM.form={querySelector:id=>({value:values[id.slice(1)]||''})};c.window.__dateFieldValue=()=> '07.09.2026';return{c,values}}
test('Fahrtformular erhält alle acht vorhandenen Felder und lehnt ungültige Kilometer ab',()=>{const {c,values}=payloadContext();assert.equal(Object.keys(c.mmPayload()).length,8);for(const bad of ['','-2','Infinity','abc']){values.mileageFormKm=bad;assert.throws(()=>c.mmPayload(),/Kilometerzahl/)}});
test('Nicht geladene Fall- oder Fahrerauswahl wird beim Speichern nicht als leere Zuordnung gesendet',()=>{const{c}=payloadContext();c.MM.casesReady=false;c.MM.driversReady=false;const p=c.mmPayload();assert.equal('caseLabel'in p,false);assert.equal('fahrerUserId'in p,false)});
test('Einreichen erfordert für Mitarbeitende eine Namensbestätigung und erlaubt keine Freigabe',()=>{const{c,values}=payloadContext();c.MM.screen='statusForm';values.mmStatus='eingereicht';assert.throws(()=>c.mmPayload(),/Namen/);values.mileageSignoffName='Ada Beispiel';assert.equal(c.mmPayload().fahrerUnterschrift,'Ada Beispiel');values.mmStatus='genehmigt';assert.throws(()=>c.mmPayload(),/Freigabeberechtigung/)});
test('Lokales Bearbeiten erhält Erstattungssnapshot, Unterschriften und fremde Metadaten',async()=>{const t=trip('a',{erstattungsbetrag:11,custom:'keep',fahrerUnterschrift:'Ada'}),c=context([t]);c.window.isBueroLocalMode=()=>true;const row=await c.mmWrite('trips','PUT','a',{fahranlass:'Korrigiert',kilometer:24,datum:t.datum});assert.equal(row.erstattungsbetrag,11);assert.equal(row.custom,'keep');assert.equal(row.fahrerUnterschrift,'Ada');assert.equal(c.saves,1)});
test('Geänderte Kilometer verwenden lokal den vorhandenen Pauschalsatz',async()=>{const c=context([trip('a')]);c.window.isBueroLocalMode=()=>true;const row=await c.mmWrite('trips','PUT','a',{kilometer:30});assert.equal(row.erstattungsbetrag,9)});
test('Lokale neue Fahrt hat eigenen Datensatz und leere Bestätigungen',async()=>{const c=context();c.window.isBueroLocalMode=()=>true;const row=await c.mmWrite('trips','POST',null,{vehicleId:'v',datum:'07.09.2026',kilometer:20});assert.equal(row.id,'new');assert.equal(row.status,'entwurf');assert.equal(row.fahrerUnterschrift,'');assert.equal(row.prueferUnterschrift,'');assert.equal(row.erstattungsbetrag,6)});
test('Lokaler Speicherfehler stellt Fahrzeuge und Fahrten wieder her',async()=>{const c=context([trip('a')]);c.window.isBueroLocalMode=()=>true;const before=JSON.stringify(c.window.bueroLocal);c.window.saveBueroLocal=()=>{throw new Error('Quota')};await assert.rejects(c.mmWrite('vehicles','DELETE','v'),/Quota/);assert.equal(JSON.stringify(c.window.bueroLocal),before)});
test('Fahrzeuglöschung entfernt lokal nur die dazugehörigen Fahrten',async()=>{const c=context([trip('a'),trip('other',{vehicleId:'other'})]);c.window.isBueroLocalMode=()=>true;await c.mmWrite('vehicles','DELETE','v');assert.equal(c.window.bueroLocal.mileageTrips.length,1);assert.equal(c.window.bueroLocal.mileageTrips[0].id,'other')});
test('Vorprüfung stoppt inzwischen veränderte Fahrten und entzogenes Bearbeitungsrecht',async()=>{const t=trip('a'),c=context([t]);c.window.isBueroLocalMode=()=>true;c.window.bueroLocal.mileageTrips[0].fahranlass='Neuer Stand';await assert.rejects(c.mmCheck('trips',[{id:'a',baseline:JSON.stringify(t)}]),/zwischenzeitlich/);assert.equal(c.MM.pending,true);c.window.__mwReadOnly=true;await assert.rejects(c.mmCheck('trips',[]),/schreibgeschützt/)});
test('Ein Server-Schreibfehler wird mit der tatsächlichen Meldung weitergereicht',async()=>{const c=context();c.fetch=async()=>({ok:false,json:async()=>({error:'Kein Zugriff auf diese Fahrt'})});await assert.rejects(c.mmWrite('trips','PUT','a',{}),/Kein Zugriff/)});
test('Fehlender Nebenabruf erhält bisherige Zuordnungen und kennzeichnet die Auswahl als ungeladen',async()=>{const c=context([trip('a')]);c.mmGet=async u=>{if(u.endsWith('trips'))return{trips:c.mileageTrips};if(u.endsWith('vehicles'))return{vehicles:c.mileageVehicles};throw new Error('offline')};const d=await c.mmRead();assert.equal(d.driversReady,false);assert.equal(d.casesReady,false);assert.equal(d.drivers[0].name,'Ada Beispiel');assert.equal(d.cases[0],'Mara');assert.match(d.warning,/Zuordnungen bleiben erhalten/)});
test('Eine ältere Antwort darf einen neueren Fahrtenabruf nicht überschreiben',async()=>{const c=context();let release;const waiting=new Promise(r=>release=r);let calls=0;c.mmRead=async()=>{const first=++calls===1;if(first)await waiting;return{vehicles:[],trips:[trip(first?'old':'new')],cases:[],drivers:[],driversReady:true,casesReady:true,warning:''}};const old=c.mmRefresh();await c.mmRefresh();release();await old;assert.equal(c.mileageTrips[0].id,'new')});
test('Ein zwischenzeitlich geöffnetes Formular verhindert den Austausch seiner Datenbasis',async()=>{const c=context([trip('keep')]);let release;c.mmRead=()=>new Promise(r=>release=r);const pending=c.mmRefresh();c.MM.form={};release({vehicles:[],trips:[trip('new')],cases:[],drivers:[]});await pending;assert.equal(c.mileageTrips[0].id,'keep')});
test('Verspätete Entfernungsberechnung erhält manuell korrigierte Kilometer',async()=>{const{c,values}=payloadContext();let release;c.window.__mileageDistanceKm=()=>new Promise(r=>release=r);const fields=Object.fromEntries(Object.entries(values).map(([id,value])=>[id,{value,dispatchEvent:()=>{}}]));c.MM.form.querySelector=id=>fields[id.slice(1)];const pending=c.mmDistance();fields.mileageFormKm.value='35';release(27.5);await pending;assert.equal(fields.mileageFormKm.value,'35')});

test('Ein während des Exports vorgemerkter Datenabruf wird nach dem Export nachgeholt',async()=>{const c=context();let reads=0;c.MM.root={querySelectorAll:()=>[],setAttribute:()=>{},removeAttribute:()=>{}};c.window.__mobileUI={guardForm:()=>({release:()=>{}})};c.mmRefresh=async()=>reads++;vm.runInContext(part('async function mmRun(','async function mmSave('),c);await c.mmRun(async()=>{c.MM.pending=true},false,false);assert.equal(reads,1);assert.equal(c.MM.busy,false)});
