'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
const script=html.split('<script id="accounting-v157-script">')[1].split('</script>')[0];
function source(a,b){const i=script.indexOf(a),j=script.indexOf(b,i);assert.ok(i>=0&&j>i,a);return script.slice(i,j)}
function context(){const c={state:{accounting:{accounts:[],invoices:[],periodFrom:'2026-01-01',periodTo:'2026-12-31'}},AM:{form:{querySelectorAll:()=>[]},guard:{busy:false},bindings:[],caseId:'a'},Event:function(){},amCanWrite:()=>true,amCase:()=> 'a',accToast:m=>c.messages.push(m),messages:[],accRenumber(){},accRunPlausibility(){},amRelease:()=>{c.AM.form=null;c.AM.guard=null},accSave:()=>c.saves++,amRefresh:()=>c.renders++,saves:0,renders:0,accReport:()=>c.state.accounting,accNorm:s=>s.toLowerCase()};vm.createContext(c);vm.runInContext(source('function amDataSnapshot(){','function amFields(')+source('function amReceiptRows(){','function amReceipts('),c);c.AM.data=c.state.accounting;c.AM.baseline=c.amDataSnapshot();return c}
test('Rechnungslegung: unveränderte Felder lösen keine Setter oder manuelle Saldenmarkierung aus',()=>{const c=context(),calls=[];c.AM.bindings=[{input:{value:'410'},value:'410',change(){calls.push('balance')}},{input:{value:'Neu'},value:'Alt',change(){calls.push('name')}}];c.amSaveForm();assert.deepEqual(calls,['name']);assert.equal(c.saves,1);assert.equal(c.renders,1)});
test('Rechnungslegung: Originalsetter werden gebündelt vor genau einer abschließenden Speicherung ausgeführt',()=>{const c=context();let batches=[];c.AM.bindings=[{input:{value:'a'},value:'',change(){batches.push(c.AM.batch)}},{input:{value:'b'},value:'',change(){batches.push(c.AM.batch)}}];c.amSaveForm();assert.deepEqual(batches,[true,true]);assert.equal(c.AM.batch,false);assert.equal(c.saves,1)});
test('Rechnungslegung: gleichzeitige Änderungen oder Fallwechsel werden vor der ersten Mutation erkannt',()=>{for(const change of ['case','object','nested']){const c=context();let writes=0;c.AM.commit=()=>writes++;if(change==='case')c.amCase=()=> 'b';if(change==='object')c.state.accounting={...c.state.accounting};if(change==='nested')c.state.accounting.accounts.push({id:'remote'});c.amSaveForm();assert.equal(writes,0);assert.equal(c.saves,0);assert.ok(c.AM.form);assert.equal(c.messages.length,1)}});
test('Rechnungslegung: Feldvalidierung und fehlende Schreibrechte lassen den Entwurf unverändert',()=>{for(const mode of ['invalid','rights']){const c=context();let writes=0;c.AM.commit=()=>writes++;if(mode==='invalid')c.AM.form.querySelectorAll=()=>[{disabled:false,checkValidity:()=>false,reportValidity(){}}];else c.amCanWrite=()=>false;c.amSaveForm();assert.equal(writes,0);assert.equal(c.saves,0);assert.ok(c.AM.form)}});
test('Rechnungslegung: Fehler beim Commit behalten das Formular und geben die Bediensperre frei',()=>{const c=context();c.AM.commit=()=>{throw new Error('Testfehler')};c.amSaveForm();assert.ok(c.AM.form);assert.equal(c.AM.busy,false);assert.equal(c.AM.batch,false);assert.equal(c.AM.guard.busy,false);assert.equal(c.saves,0);assert.match(c.messages[0],/Testfehler/)});
test('Rechnungslegung: belegbezogene Filter kombinieren Erkennungszustand, Auswahl und Volltext',()=>{const c=context();c.state.accounting.invoices=[{id:'ok',name:'Strom',issuer:'Stadtwerke',total:30,confidence:1,selected:true,status:'ready',assignments:[{}]},{id:'err',name:'Scan',issuer:'',total:null,status:'error',assignments:[]},{id:'other',name:'Miete',issuer:'Vermieter',total:200,confidence:1,status:'ready',assignments:[]}];c.AM.receiptQuery='';c.AM.receiptStatus='unassigned';assert.deepEqual(Array.from(c.amReceiptRows(),x=>x.id),['err','other']);c.AM.receiptStatus='selected';assert.equal(c.amReceiptRows()[0].id,'ok');c.AM.receiptStatus='error';assert.equal(c.amReceiptRows()[0].id,'err');c.AM.receiptStatus='all';c.AM.receiptQuery='Stadtwerke';assert.equal(c.amReceiptRows()[0].id,'ok')});
test('Rechnungslegung: Aktualisierung bewahrt Formulare und laufende Vorgänge, gibt neue Fälle aber frei',()=>{const c={AM:{form:{},caseId:'a'},amOwned:()=>true,amCase:()=> 'a',amEnabled:()=>true,currentReport:'accounting',ACC_ID:'accounting',amRelease:()=>{c.AM.form=null},queueMicrotask:fn=>c.queued=fn,amAdopt(){}};vm.createContext(c);vm.runInContext(source('function amBeforeRender(){','function amRefresh(){'),c);assert.equal(c.amBeforeRender(),true);assert.equal(c.AM.pending,true);c.amCase=()=> 'b';assert.equal(c.amBeforeRender(),false);assert.equal(c.AM.form,null);assert.ok(c.queued)});
