'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8'),script=html.split('<script id="schuldenregulierung-script-v1">')[1].split('</script>')[0];
function source(a,b){const i=script.indexOf(a),j=script.indexOf(b,i);assert.ok(i>=0&&j>i,a);return script.slice(i,j)}
const debt=(id,extra={})=>({id,glaeubiger:'Kreditbank',kategorie:'Darlehen',aktenzeichen:'AZ-1',hauptforderung:'1000',mahnkosten:'20',bearbeitungskosten:'10',prozesskosten:'5',basisGezahlt:'100',ratenhoehe:'50',ratenintervall:'monatlich',status:'ratenzahlung',dauerauftrag:false,bankverbindung:{iban:'original',custom:'bank-meta'},payments:[{id:'p1',datum:'2026-09-01',betrag:'50',hinweis:'Rate',ausHandkasse:true}],custom:{keep:true},...extra});
function context(rows=[]){const c={window:{},state:{caseData:{schuldenregulierung:rows,livelihood:{income:[],expenses:[]},assets:{begin:[],end:[],debtsBegin:[],debtsEnd:[]},handkasse:[]}},SRM:{tab:'debts',query:'',caseFilter:'all',status:'all',creditor:'all',payment:'all',route:'all',year:'all',sort:'rest',caseId:'a',id:'',screen:'form',draft:null},SR_IMPORT_KEYS:['forderungsbeginn','glaeubiger','kategorie','aktenzeichen','hauptforderung','mahnkosten','bearbeitungskosten','prozesskosten','ratenhoehe','ratenintervall','status','verwendungszweck','notizen','basisGezahlt'],srScope:'self',srFilter:'alle',num:v=>parseFloat(String(v??'').replace(',','.'))||0,euro:v=>String(v),srmCanWrite:()=>true,srmCase:()=> 'a',srmName:()=> 'Fall A',nid:()=> 'new-debt',pid:()=> 'new-payment',todayIso:()=> '2026-09-07',srAllDebts:()=>c.all||[],srSyncFristen(){},schuldRefreshInd(){},saveState:()=>c.saves++,saves:0,SR_STATUS:[['offen','Offen'],['ratenzahlung','In Ratenzahlung'],['pausiert','Pausiert'],['erledigt','Erledigt']]};vm.createContext(c);vm.runInContext(source('function srData(){','// Datum des Schuldenabbaus:')+source('function passFilter(','// ---- Eingabe-Zellen')+source('function srAssetCategory(','function srPersist(){')+source('function srPayoffIso(','function srMaybeSyncFrist(')+source('function srmAll(','function srmRender(')+source('function srmSnapshot(','function srmError('),c);c.srPersist=()=>{c.srSyncMirrors();c.saveState()};c.SRM.context=c.state.caseData;return c}
function edit(c,d,screen='form',payId=''){Object.assign(c.SRM,{id:d.id,baseline:JSON.stringify(d),screen,payId})}
function values(d){return{...d,'bank.kontoinhaber':d.bankverbindung?.kontoinhaber||'','bank.iban':d.bankverbindung?.iban||'','bank.bic':d.bankverbindung?.bic||'','bank.bank':d.bankverbindung?.bank||''}}
test('Schulden: alle Kosten und Zahlungen gehen in Forderung und Restschuld ein',()=>{const d=debt('a'),c=context([d]);assert.equal(c.forderungshoehe(d),1035);assert.equal(c.gezahlt(d),150);assert.equal(c.restschuld(d),885);assert.equal(c.monthlyRate(d),50)});
test('Schulden: Historie, Stadium, Gläubiger, Zahlungsstand und Suche kombinieren sich',()=>{const a=debt('a'),b=debt('b',{glaeubiger:'Stadtwerke',status:'offen'}),c=context([a,b]);Object.assign(c.SRM,{status:'ratenzahlung',creditor:'Kreditbank',payment:'paid',query:'az-1'});assert.deepEqual(Array.from(c.srmRows(),x=>x.d.id),['a']);c.srFilter='historisch';assert.equal(c.srmRows().length,0)});
test('Schulden: büroweite Treffer behalten Fallkennung bei gleichen Forderungskennungen',()=>{const a=debt('same'),b=debt('same',{glaeubiger:'Anderer Gläubiger'}),c=context([a]);c.srScope='all';c.all=[{caseId:'a',caseLabel:'A',d:a},{caseId:'b',caseLabel:'B',d:b}];assert.equal(c.srmRows().length,2);assert.equal(c.srmItem('b','same').d,b);c.SRM.caseFilter='b';assert.equal(c.srmRows().length,1);assert.equal(c.srmEditable(c.all[0]),false)});
test('Schulden: Zahlungsjahr und Handkassenfilter arbeiten auf Einzelzahlungen',()=>{const d=debt('a');d.payments.push({id:'old',datum:'2025-01-01',betrag:30,ausHandkasse:false});const c=context([d]);c.SRM.year='2026';c.SRM.route='cash';assert.deepEqual(Array.from(c.srmPayments(),x=>x.p.id),['p1']);c.SRM.route='other';assert.equal(c.srmPayments().length,0)});
test('Schulden: Bearbeitung erhält Metadaten und spiegelt Forderung, Restschuld, Rate und Bargeld korrekt',()=>{const d=debt('a'),c=context([d]);edit(c,d);c.srmCommit({...values(d),hauptforderung:'1100',ratenhoehe:'60'});assert.equal(d.custom.keep,true);assert.equal(d.bankverbindung.custom,'bank-meta');assert.equal(d.payments[0].id,'p1');assert.equal(c.state.caseData.assets.debtsBegin[0].amount,1135);assert.equal(c.state.caseData.assets.debtsEnd[0].amount,985);assert.equal(c.state.caseData.livelihood.expenses[0].monthly,60);assert.equal(c.state.caseData.handkasse[0].amount,50);assert.equal(c.saves,1)});
test('Schulden: neue Forderung übernimmt alle Kosten und Bankfelder ohne vorzeitige Mutation',()=>{const c=context(),d=debt('draft');c.SRM.draft=d;assert.equal(c.state.caseData.schuldenregulierung.length,0);const r=c.srmCommit(values(d));assert.equal(r.id,'draft');assert.equal(c.state.caseData.schuldenregulierung[0].prozesskosten,'5');assert.equal(c.state.caseData.schuldenregulierung[0].bankverbindung.iban,'original');assert.equal(c.saves,1)});
test('Schulden: neue Barzahlung spiegelt sich exakt einmal in Vermögen und Handkasse',()=>{const d=debt('a'),c=context([d]);edit(c,d,'payment-form');c.srmCommit({datum:'2026-09-07',betrag:'25.50',hinweis:'Bar gezahlt',ausHandkasse:'on'});assert.equal(d.payments.length,2);assert.equal(c.state.caseData.handkasse.length,2);assert.equal(c.state.caseData.handkasse.find(x=>x.sourcePayId==='new-payment').amount,25.5);assert.equal(c.state.caseData.assets.debtsEnd[0].amount,859.5);assert.equal(c.saves,1)});
test('Schulden: Bearbeitung einer Zahlung erhält deren Kennung und entfernt eine aufgehobene Barspiegelung',()=>{const d=debt('a'),c=context([d]);edit(c,d,'payment-form','p1');c.srmCommit({datum:'2026-09-02',betrag:'55',hinweis:'Korrigiert'});assert.equal(d.payments.length,1);assert.equal(d.payments[0].id,'p1');assert.equal(d.payments[0].ausHandkasse,false);assert.equal(c.state.caseData.handkasse.length,0)});
test('Schulden: Statuswechsel setzt und entfernt Erledigungs- und Pausendaten',()=>{const d=debt('a'),c=context([d]);edit(c,d);c.srmCommit({...values(d),status:'pausiert'});assert.equal(d.pausiertSeit,'2026-09-07');assert.equal(c.state.caseData.livelihood.expenses.length,0);edit(c,d);c.srmCommit({...values(d),status:'erledigt'});assert.equal(d.erledigtAm,'2026-09-07');assert.equal(d.pausiertSeit,'');edit(c,d);c.srmCommit({...values(d),status:'ratenzahlung'});assert.equal(d.erledigtAm,'');assert.equal(c.state.caseData.livelihood.expenses.length,1)});
test('Schulden: Fallwechsel, entfernte Forderung und konkurrierende Zahlungen blockieren ältere Entwürfe',()=>{for(const change of ['case','reload','payment','delete']){const d=debt('a'),c=context([d]);edit(c,d);if(change==='case')c.srmCase=()=> 'b';if(change==='reload')c.state.caseData={...c.state.caseData};if(change==='payment')d.payments.push({id:'other',betrag:'1'});if(change==='delete')c.state.caseData.schuldenregulierung=[];assert.throws(()=>c.srmCommit(values(d)));assert.equal(c.saves,0)}});
test('Schulden: Speicherfehler rollt sämtliche Finanzspiegelungen zurück',()=>{const d=debt('a'),c=context([d]);edit(c,d);const before=JSON.stringify(c.state);c.saveState=()=>{throw new Error('Speicherfehler')};assert.throws(()=>c.srmCommit({...values(d),hauptforderung:'9999'}),/Speicherfehler/);assert.equal(JSON.stringify(c.state),before)});
test('Schulden: Leseberechtigte und ungültige Beträge schreiben nichts',()=>{for(const mode of ['reader','amount']){const d=debt('a'),c=context([d]);edit(c,d);if(mode==='reader')c.srmCanWrite=()=>false;assert.throws(()=>c.srmCommit({...values(d),hauptforderung:mode==='amount'?'NaN':'100'}));assert.equal(c.saves,0)}});

test('Schulden: Zahlungssuche findet nur die passende Einzelzahlung statt aller Zahlungen derselben Forderung',()=>{const d=debt('a');d.payments.push({id:'second',datum:'2026-09-03',betrag:'15',hinweis:'Sonderzahlung'});const c=context([d]);c.SRM.query='sonderzahlung';assert.deepEqual(Array.from(c.srmPayments(),x=>x.p.id),['second']);c.SRM.query='2026-09-01';assert.deepEqual(Array.from(c.srmPayments(),x=>x.p.id),['p1'])});
