'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.resolve(__dirname,'../../outputs/Betreuungsbuero_Dokumentenassistent_v0_7.html'),'utf8');
const script=id=>html.split('<script id="'+id+'">')[1].split('</script>')[0],plan=script('finance-script-v1'),book=script('finance-belege-script-v1');
function part(s,a,b){const i=s.indexOf(a),j=s.indexOf(b,i);assert.ok(i>=0&&j>i,a);return s.slice(i,j)}
const entry=(id,extra={})=>({id,kind:'ausgabe',posten:'Miete',partner:'Vermietung',frequenz:'monatlich',summeGesamt:850,summeMonatlich:850,konto:'geschaeftlich',datum:null,...extra});
function planContext(rows=[]){const c={window:{isBueroLocalMode:()=>true,bueroLocal:{financeEntries:rows},newBueroLocalId:()=> 'new',saveBueroLocal:()=>c.saves++},financeEntries:rows,financePlanFilterJahr:'alle',FREQUENZ_LABELS:{monatlich:'Monatlich',jaehrlich:'Jährlich',einmalig:'Einmalig'},FPM:{tab:'laufend',query:'',kind:'alle',konto:'alle',partner:'alle',frequency:'alle',person:'alle',sort:'original'},fpmRight:()=>true,financeDarfPersonen:()=>true,toast:()=>{},kontoLabel:k=>k==='privat'?'Privat':'Geschäftlich',saves:0};vm.createContext(c);vm.runInContext(part(plan,'function financePlanJahr(','function financePlanJahre(')+part(plan,'function financeSums(','function financeRowActions(')+part(plan,'function fpmPerson(','function fpmMount(')+part(plan,'function fpmPayload(','function fpmError('),c);return c}
test('Büroplanung: laufende Monatswerte bleiben von Frequenz und Jahresfilter unabhängig',()=>{const c=planContext([entry('rent'),entry('annual',{frequenz:'jaehrlich',summeGesamt:1200,summeMonatlich:80}),entry('in',{kind:'einnahme',summeMonatlich:2000}),entry('once',{frequenz:'einmalig',summeGesamt:5000,datum:'2025-01-01'})]);c.financePlanFilterJahr='2026';assert.equal(c.financeSums().bilanz,1070);assert.equal(c.fpmRows('laufend').length,3);assert.equal(c.fpmRows('einmalig').length,0)});
test('Büroplanung: Art, Konto, Partner, Person, Frequenz und Volltext sind kombinierbar',()=>{const c=planContext([entry('a',{personKennung:'MA-001'}),entry('b',{konto:'privat'}),entry('c',{kind:'einnahme'})]);Object.assign(c.FPM,{kind:'ausgabe',konto:'geschaeftlich',partner:'Vermietung',person:'MA-001',frequency:'monatlich',query:'MA-001'});assert.deepEqual(Array.from(c.fpmRows(),x=>x.id),['a'])});
test('Büroplanung: undatierte Einmalposten werden trotz laufender Frequenzauswahl gefunden',()=>{const c=planContext([entry('a',{frequenz:'einmalig',datum:''}),entry('b',{frequenz:'einmalig',datum:'2026-09-01'})]);c.financePlanFilterJahr='ohne';c.FPM.frequency='monatlich';assert.deepEqual(Array.from(c.fpmRows('einmalig'),x=>x.id),['a'])});
test('Büroplanung: Sortieren verändert die gespeicherte Reihenfolge nicht',()=>{const c=planContext([entry('a',{summeMonatlich:1}),entry('b',{summeMonatlich:99})]);c.FPM.sort='amount';assert.equal(c.fpmRows()[0].id,'b');assert.equal(c.financeEntries[0].id,'a')});
test('Büroplanung: lokales Speichern erhält Metadaten, Personen und explizite Nullbeträge',async()=>{const e=entry('a',{personId:'p',custom:'keep'}),c=planContext([e]);const r=await c.fpmPersist('PUT','a',{...e,summeGesamt:'0',summeMonatlich:'0'},JSON.stringify(e));assert.equal(r.custom,'keep');assert.equal(r.personId,'p');assert.equal(r.summeMonatlich,0);assert.equal(c.saves,1)});
test('Büroplanung: eine zwischenzeitliche Änderung verhindert das Überschreiben',async()=>{const e=entry('a'),c=planContext([e]),before=JSON.stringify(e);e.posten='Neuer Stand';await assert.rejects(c.fpmPersist('PUT','a',{posten:'Alt'},before),/zwischenzeitlich/);assert.equal(c.saves,0);assert.equal(e.posten,'Neuer Stand')});
test('Büroplanung: fehlende Schreibrechte verhindern jeden Schreibzugriff',async()=>{const c=planContext();c.fpmRight=()=>false;await assert.rejects(c.fpmPersist('POST',null,entry('a')),/Berechtigung/);assert.equal(c.saves,0)});
test('Büroplanung: lokaler Speicherfehler stellt den bisherigen Bestand wieder her',async()=>{const e=entry('a'),c=planContext([e]),before=JSON.stringify(c.window.bueroLocal);c.window.saveBueroLocal=()=>{throw new Error('Speicherfehler')};await assert.rejects(c.fpmPersist('PUT','a',{...e,posten:'Änderung'},JSON.stringify(e)),/Speicherfehler/);assert.equal(JSON.stringify(c.window.bueroLocal),before)});
test('Büroplanung: nicht geladene oder nicht berechtigte Personenauswahl wird nicht mitgesendet',()=>{const c=planContext();const values={financeFormKind:'ausgabe',financeFormPosten:'Gehalt',financeFormFrequenz:'monatlich',financeFormSummeGesamt:'0',financeFormSummeMonatlich:'0',financeFormKonto:'geschaeftlich'},person={value:'',dataset:{}};c.FPM.form={querySelector:s=>s==='#financeFormPerson'?person:{value:values[s.slice(1)]||''}};assert.equal('personId'in c.fpmPayload(),false);person.dataset.geladen='1';c.financeDarfPersonen=()=>false;assert.equal('personId'in c.fpmPayload(),false);c.financeDarfPersonen=()=>true;person.value='p';assert.equal(c.fpmPayload().personId,'p')});
function bookContext(){const c={window:{isBueroLocalMode:()=>true,bueroLocal:{financeEntries:[]}},financeLocalSession:{statements:[],transactions:[],receipts:[]},financeLocalFileBytes:new Map(),financeStatements:[],financeTransactions:[],financeReceiptsDetail:[],financeEntriesForMatch:[],financeDatenStand:0,financeReadGeneration:0,FDM:{query:'',sort:'new',statement:'',direction:'alle',attachment:'alle',receiptStatus:'alle',parse:'alle'},financeDetailFilterKonto:'alle',financeDetailFilterYear:'alle',financeDetailFilterStatus:'alle',financeDetailFilterBuchung:'',fdmMobile:()=>true,fdmOwned:()=>true,financeOcrJobs:new Map(),fdmRight:()=>true,flId:()=> 'new',Blob,Uint8Array,atob:s=>Buffer.from(s,'base64').toString('binary'),btoa:s=>Buffer.from(s,'binary').toString('base64'),console};vm.createContext(c);vm.runInContext(part(book,'function flRes(','async function financeLocalRoute(')+part(book,'async function financeLocalRoute(','/* V212')+part(book,'function financeFileBase64(','async function ffetch(')+part(book,'async function loadFinanceDetailData(','function fmtEuroDetail(')+part(book,'function financeFilteredTransactions(','function financeYearOfDate(')+part(book,'function financeYearOfDate(','function financeDedupTransactions(')+part(book,'function financeReceiptYear(','function financeBulkSet(')+part(book,'function financeStatementYears(','function financeYearValues(')+part(book,'function fdmExtraRows(','function fdmRows('),c);c.financeDedupTransactions=x=>x;c.financeStatementStatusLabel=x=>x.parseStatus;c.ffetch=async u=>({ok:true,json:async()=>{const key=u.split('/').at(-1);return{[key]:c.mock?.[key]||[]}}});return c}
test('Buchhaltung: Suche und Belegfilter erfassen exakt die passenden Einzelbuchungen',()=>{const c=bookContext();c.financeTransactions=[{id:'a',purpose:'Miete',amount:-850,konto:'geschaeftlich'},{id:'b',purpose:'Software',amount:-100,konto:'geschaeftlich'}];c.financeReceiptsDetail=[{id:'r',matchedTransactionId:'a'}];c.FDM.attachment='without';assert.deepEqual(Array.from(c.financeFilteredTransactions(),x=>x.id),['b']);c.FDM.query='MIETE';assert.equal(c.financeFilteredTransactions().length,0)});
test('Buchhaltung: Auszugsfilter und Jahr über Jahresgrenzen bleiben kombinierbar',()=>{const c=bookContext();c.financeStatements=[{id:'a',konto:'geschaeftlich',uploadedAt:'2026-01-01',parseStatus:'done'}];c.financeTransactions=[{statementId:'a',bookingDate:'2025-12-31'},{statementId:'a',bookingDate:'2026-01-01'}];c.financeDetailFilterYear='2025';c.FDM.parse='done';assert.equal(c.financeFilteredStatements().length,1);c.financeDetailFilterKonto='privat';assert.equal(c.financeFilteredStatements().length,0)});
test('Buchhaltung: Belegstatus, Volltext und Jahresfilter berücksichtigen die vorhandene Zuordnung',()=>{const c=bookContext();c.financeReceiptsDetail=[{id:'a',issuer:'Vermietung',invoiceDate:'2026-09-01',matchedTransactionId:'tx',ocrStatus:'done'},{id:'b',issuer:'Software',invoiceDate:'2025-09-01',matchedTransactionId:null,ocrStatus:'failed'}];c.FDM.receiptStatus='matched';c.FDM.query='vermiet';c.financeDetailFilterYear='2026';assert.deepEqual(Array.from(c.financeFilteredReceipts(),x=>x.id),['a'])});
test('Buchhaltung: ein fehlgeschlagener Teilabruf ersetzt keine der vier vorhandenen Listen',async()=>{const c=bookContext();c.financeStatements=[{id:'old'}];c.ffetch=async u=>({ok:!u.endsWith('receipts'),status:u.endsWith('receipts')?503:200,json:async()=>({[u.split('/').at(-1)]:[{id:'new'}]})});await assert.rejects(c.loadFinanceDetailData(true),/vollständig/);assert.equal(c.financeStatements[0].id,'old');assert.equal(c.financeDatenStand,0)});
test('Buchhaltung: eine verspätete ältere Antwort überschreibt den neueren Abruf nicht',async()=>{const c=bookContext();let release;const pending=new Promise(r=>release=r);let first=true;c.ffetch=async u=>{const key=u.split('/').at(-1),old=first;if(key==='entries')first=false;return{ok:true,json:async()=>{if(old&&key==='statements')await pending;return{[key]:[{id:old?'old':'new'}]}}}};const one=c.loadFinanceDetailData(true);await c.loadFinanceDetailData(true);release();await one;assert.equal(c.financeStatements[0].id,'new')});
test('Buchhaltung: große Dateien werden ohne Argumentlisten-Überlauf nach Base64 umgewandelt',()=>{const c=bookContext(),bytes=Uint8Array.from({length:400000},(_,i)=>i%251);assert.equal(c.financeFileBase64(bytes.buffer),Buffer.from(bytes).toString('base64'))});
test('Buchhaltung lokal: Auszugsmetadaten lassen sich über den bestehenden Endpunkt ändern',async()=>{const c=bookContext();c.financeLocalSession.statements=[{id:'s',filename:'Alt.pdf',konto:'privat'}];const r=await c.financeLocalRoute('/api/finance/statements/s',{method:'PUT',body:JSON.stringify({filename:'Neu.pdf',konto:'geschaeftlich'})});assert.equal(r.ok,true);assert.equal(c.financeLocalSession.statements[0].filename,'Neu.pdf')});
test('Buchhaltung lokal: Auszugslöschung löst nur die betroffenen Belegverbindungen',async()=>{const c=bookContext();c.financeLocalSession.statements=[{id:'s'}];c.financeLocalSession.transactions=[{id:'t',statementId:'s'},{id:'other',statementId:'other'}];c.financeLocalSession.receipts=[{id:'r',matchedTransactionId:'t',status:'zugeordnet'},{id:'keep',matchedTransactionId:'other'}];await c.financeLocalRoute('/api/finance/statements/s',{method:'DELETE'});assert.equal(c.financeLocalSession.receipts[0].matchedTransactionId,null);assert.equal(c.financeLocalSession.receipts[1].matchedTransactionId,'other');assert.equal(c.financeLocalSession.transactions.length,1)});
test('Buchhaltung lokal: erneuter Auszugsimport setzt Parsezustand und ersetzt die Buchungen',async()=>{const c=bookContext();c.financeLocalSession.statements=[{id:'s',parseStatus:'pending',konto:'privat'}];c.financeLocalSession.transactions=[{id:'old',statementId:'s'}];c.financeLocalSession.receipts=[{matchedTransactionId:'old'}];await c.financeLocalRoute('/api/finance/statements/s/transactions',{method:'POST',body:JSON.stringify({transactions:[{amount:10}]})});assert.equal(c.financeLocalSession.statements[0].parseStatus,'done');assert.equal(c.financeLocalSession.transactions.length,1);assert.equal(c.financeLocalSession.transactions[0].konto,'privat');assert.equal(c.financeLocalSession.receipts[0].matchedTransactionId,null)});
test('Buchhaltung lokal: Originaldatei und OCR-Text bleiben nur in der Sitzung verfügbar',async()=>{const c=bookContext();c.financeLocalSession.receipts=[{id:'r',mimeType:'application/pdf',ocrText:'Test'}];c.financeLocalFileBytes.set('receipt:r',Buffer.from('PDF-TEST').toString('base64'));const file=await c.financeLocalRoute('/api/finance/receipts/r/file',{}),text=await c.financeLocalRoute('/api/finance/receipts/r/text',{});assert.equal(await (await file.blob()).text(),'PDF-TEST');assert.equal((await text.json()).text,'Test');assert.deepEqual(Object.keys(c.window.bueroLocal),['financeEntries'])});

test('Büroplanung: entzogene Klarnamenberechtigung verbirgt auch zuvor geladene Namen',()=>{const c=planContext();const e=entry('a',{personName:'Ada Beispiel',personKennung:'MA-001'});assert.match(c.fpmPerson(e),/Ada Beispiel/);c.financeDarfPersonen=()=>false;assert.equal(c.fpmPerson(e),'MA-001')});
